execute_process(
  COMMAND "${CLI}" --version
  RESULT_VARIABLE VERSION_RESULT
  OUTPUT_VARIABLE VERSION_OUTPUT
  ERROR_VARIABLE VERSION_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT VERSION_RESULT EQUAL 0)
  message(FATAL_ERROR "--version failed: ${VERSION_ERROR}")
endif()
if(NOT VERSION_OUTPUT STREQUAL "KairosBoot ${EXPECTED_VERSION}")
  message(FATAL_ERROR "unexpected --version output: ${VERSION_OUTPUT}")
endif()

execute_process(
  COMMAND "${CLI}" --version --json
  RESULT_VARIABLE JSON_VERSION_RESULT
  OUTPUT_VARIABLE JSON_VERSION_OUTPUT
  ERROR_VARIABLE JSON_VERSION_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT JSON_VERSION_RESULT EQUAL 0)
  message(FATAL_ERROR "--version --json failed: ${JSON_VERSION_ERROR}")
endif()
string(JSON JSON_VERSION GET "${JSON_VERSION_OUTPUT}" version)
string(JSON JSON_API_VERSION GET "${JSON_VERSION_OUTPUT}" apiVersion)
if(NOT JSON_VERSION STREQUAL EXPECTED_VERSION OR NOT JSON_API_VERSION EQUAL 1)
  message(FATAL_ERROR "unexpected version JSON: ${JSON_VERSION_OUTPUT}")
endif()

execute_process(
  COMMAND "${CLI}" doctor --json
  RESULT_VARIABLE DOCTOR_RESULT
  OUTPUT_VARIABLE DOCTOR_OUTPUT
  ERROR_VARIABLE DOCTOR_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT DOCTOR_RESULT EQUAL 0)
  message(FATAL_ERROR "doctor failed: ${DOCTOR_ERROR}")
endif()
string(JSON DOCTOR_OK GET "${DOCTOR_OUTPUT}" ok)
string(JSON DOCTOR_TRANSPORT GET "${DOCTOR_OUTPUT}" transport available)
string(JSON DOCTOR_DEVICE_COUNT GET "${DOCTOR_OUTPUT}" deviceCount)
if(NOT DOCTOR_OK OR NOT DOCTOR_TRANSPORT OR DOCTOR_DEVICE_COUNT LESS 0)
  message(FATAL_ERROR "unexpected doctor JSON: ${DOCTOR_OUTPUT}")
endif()

execute_process(
  COMMAND "${CLI}" devices --json
  RESULT_VARIABLE DEVICES_RESULT
  OUTPUT_VARIABLE DEVICES_OUTPUT
  ERROR_VARIABLE DEVICES_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT DEVICES_RESULT EQUAL 0)
  message(FATAL_ERROR "devices --json failed: ${DEVICES_ERROR}")
endif()
string(JSON DEVICES_OK GET "${DEVICES_OUTPUT}" ok)
string(JSON DEVICES_TYPE TYPE "${DEVICES_OUTPUT}" devices)
if(NOT DEVICES_OK OR NOT DEVICES_TYPE STREQUAL "ARRAY")
  message(FATAL_ERROR "unexpected devices JSON: ${DEVICES_OUTPUT}")
endif()
