execute_process(
  COMMAND "${CLI}" --version
  RESULT_VARIABLE VERSION_RESULT
  OUTPUT_VARIABLE VERSION_OUTPUT
  ERROR_VARIABLE VERSION_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT VERSION_RESULT EQUAL 0)
  message(FATAL_ERROR "--version failed: ${VERSION_ERROR}")
endif()
if(NOT VERSION_OUTPUT STREQUAL "KairosBoot ${EXPECTED_VERSION}")
  message(FATAL_ERROR "unexpected --version output: ${VERSION_OUTPUT}")
endif()

execute_process(
  COMMAND "${CLI}" --version --json
  RESULT_VARIABLE JSON_VERSION_RESULT
  OUTPUT_VARIABLE JSON_VERSION_OUTPUT
  ERROR_VARIABLE JSON_VERSION_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT JSON_VERSION_RESULT EQUAL 0)
  message(FATAL_ERROR "--version --json failed: ${JSON_VERSION_ERROR}")
endif()
string(JSON JSON_VERSION GET "${JSON_VERSION_OUTPUT}" version)
string(JSON JSON_API_VERSION GET "${JSON_VERSION_OUTPUT}" apiVersion)
if(NOT JSON_VERSION STREQUAL EXPECTED_VERSION OR NOT JSON_API_VERSION EQUAL 1)
  message(FATAL_ERROR "unexpected version JSON: ${JSON_VERSION_OUTPUT}")
endif()

execute_process(
  COMMAND "${CLI}" doctor --json
  RESULT_VARIABLE DOCTOR_RESULT
  OUTPUT_VARIABLE DOCTOR_OUTPUT
  ERROR_VARIABLE DOCTOR_ERROR
  OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT DOCTOR_RESULT EQUAL 4)
  message(FATAL_ERROR "doctor must report unavailable transport: ${DOCTOR_ERROR}")
endif()
string(JSON DOCTOR_OK GET "${DOCTOR_OUTPUT}" ok)
string(JSON DOCTOR_STATUS GET "${DOCTOR_OUTPUT}" transport status)
if(DOCTOR_OK OR NOT DOCTOR_STATUS STREQUAL "not_supported")
  message(FATAL_ERROR "unexpected doctor JSON: ${DOCTOR_OUTPUT}")
endif()
